springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}

fracexec:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}

logging:
  level:
    com.fracexec: INFO
    root: WARN
